services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_URLS=http://+80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DatabaseConnectionString=Host=postgres-expense;username=postgres;password=qwerty;database=expensedb;TrustServerCertificate=True;
    depends_on:
      - postgres-expense

  postgres-expense:
    image: postgres:alpine
    restart: always
    container_name: postgres-expense
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    environment:
      POSTGRES_DB: expensedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
     - "5432:5432"
    
volumes:
 postgres_data: