name: Build .Net Api

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup dotnet api
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      - name: Install Dependencies
        run: |
          dotnet restore
        
      - name: Build 
        run: |
          dotnet build
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sagar116/expensetrakcer-api:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploying
        run: |
          echo "Deploy"

